version: '3'
services:
    api-hotel: 
      image: api-hotel:latest
      container_name: api-hotel
      restart: always
      ports:
        - 3000:3000
      volumes: 
        - ./.env:/opt/app/.env
