version: '3'
services:
    api-hotel: 
      image: ghcr.io/egprichina/hotel_api/api_hotel:develop
      container_name: api-hotel
      restart: always
      ports:
        - 3000:3000
      volumes: 
        - ./.env:/opt/app/.env
